[package]
name = "thingbuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ["alloc"]
alloc = []
default = ["std"]

[dependencies]

[dev-dependencies]
loom = { version = "0.5", features = ["checkpoint", "futures"] }
# So that we can use `poll_fn` in tests.
futures = "0.3"
criterion = { version = "0.3.5", features = ["async_tokio"] }
# for comparison benchmarks
crossbeam = "0.8.1"
tokio = { version = "1.14.0", features = ["rt", "sync"] }
async-std = "1"

[profile.test]
opt-level = 3

[patch.crates-io]
loom = { git = "https://github.com/tokio-rs/loom", branch = "master"}

[[bench]]
name = "sync_mpsc"
harness = false

[[bench]]
name = "async_mpsc"
harness = false
